services:
  jem_db:
    image: postgres:latest
    container_name: jem_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jem_api:
    build: ./apps/jem-api
    container_name: jem_api
    restart: always
    depends_on:
      - jem_db
    ports:
      - "3000:3000"
    volumes:
      - ./apps/jem-api:/app
      - /app/node_modules
    env_file:
      - .env

  jem_back:
    build: ./apps/jem-back
    container_name: jem_back
    restart: always
    depends_on:
      - jem_api
    ports:
      - "4000:4000"
    volumes:
      - ./apps/jem-back:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  pgdata:
